### ISSUE TITLE
running in virtualbox: missing drivers error in octopi

### ISSUE THREAD

**Issue by star-buck** [netrunner-rolling/netrunner-rolling-issues#2]
Here is a screenshot:
![snap 2015-10-05 at 11 04 06](https://cloud.githubusercontent.com/assets/840070/10276651/10b85fac-6b51-11e5-9a26-a2c6cf7b7044.png)
Maybe this can be fixed with installing additional packages on the ISO?

**Comment by star-buck** [comment]
can be seen here: https://www.youtube.com/watch?v=SGP1dfagfoY#t=480

**Comment by AJSlye** [comment]
This error is because you need to have the guest addons installed for dri and/or, dri2 to be available in vbox.
 
![snapshot1](https://cloud.githubusercontent.com/assets/10186587/10533122/57b10a72-7393-11e5-94a7-2dea4bd788d6.png)

**Comment by AJSlye** [comment]
Adding this to this ISO is huge and pushes the ISO over 2 gig. The review should have known to install the virtual box guest additions from either the distributions repositories or from within virtual box itself.
https://www.virtualbox.org/manual/ch04.html
